[package]
name = "lesp"
version = "0.1.0"
authors = ["mail@profpatsch.de"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.5.*"

[build-dependencies]
cc = "1.0.*"
